version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

  pre_build:
    commands:
      - pip install -r requirements.txt

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/house-price-app

      - echo Logging in to Amazon ECR...

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo "Training model..."
      - python src/train.py

      - echo "Running tests..."
      - pytest tests/

      - echo "Building Docker image..."
      - docker build -t house-price-app .

      - docker tag house-price-app:latest $REPO_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."

      - docker push $REPO_URI:latest

      - printf '[{"name":"house-price-app","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json